const listings = [
  {
    title: 'Lakeside Terrace',
    description: 'Great propertyGreat propertyGreat propertyGreat property',
    address: {
      street: '2134 Main St',
      city: 'Houston',
      state: 'TX',
      zipcode: '770072',
    },
    price: 100000,
    bedrooms: 6,
    garage: 2,
    sqft: 50000,
    lot_size: 12,
    photo_1: 'no-photo.jpg',
    photo_2: 'no-photo.jpg',
    photo_3: 'no-photo.jpg',
    photo_4: 'no-photo.jpg',
    photo_5: 'no-photo.jpg',
    photo_6: 'no-photo.jpg',
    is_Published: false,
  },
  {
    title: 'Waterfront Terrace',
    description: 'Great propertyGreat propertyGreat propertyGreat property',
    address: {
      street: '2134 Main St',
      city: 'Houston',
      state: 'TX',
      zipcode: '770072',
    },
    price: 100000,
    bedrooms: 6,
    garage: 2,
    sqft: 50000,
    lot_size: 12,
    photo_1: 'no-photo.jpg',
    photo_2: 'no-photo.jpg',
    photo_3: 'no-photo.jpg',
    photo_4: 'no-photo.jpg',
    photo_5: 'no-photo.jpg',
    photo_6: 'no-photo.jpg',
    is_Published: false,
  },
  {
    title: 'Homefront Terrace',
    description: 'Great propertyGreat propertyGreat propertyGreat property',
    address: {
      street: '2134 Main St',
      city: 'Houston',
      state: 'TX',
      zipcode: '770072',
    },
    price: 100000,
    bedrooms: 6,
    garage: 2,
    sqft: 50000,
    lot_size: 12,
    photo_1: 'no-photo.jpg',
    photo_2: 'no-photo.jpg',
    photo_3: 'no-photo.jpg',
    photo_4: 'no-photo.jpg',
    photo_5: 'no-photo.jpg',
    photo_6: 'no-photo.jpg',
    is_Published: false,
  },
]

export default listings
